name: CI/CD S107

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests
    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Package
      run: zip -r package.zip ./

    - name: Upload Build Package
      uses: actions/upload-artifact@v3
      with:
        name: build-package
        path: package.zip

  notify:
    needs: [tests, build]
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification Email
      run: |
        echo "Pipeline executado com sucesso!" | mail -s "Notificação do Pipeline" ${{ secrets.EMAIL }}
